import type { Metadata } from "next";
import "./globals.css";
import { NeueMontreal } from "../../public/font";
import { Nav } from "@/components/fragments";
import { Time } from "@/components/ui";

const font = NeueMontreal;

export const metadata: Metadata = {
  title: "Marlon Martin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-base p-4 text-white w-full h-screen overflow-hidden ${font.className}`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
