import type { Metadata } from "next";
import "./globals.css";
import { NeueMontreal } from "../../public/font";

const font = NeueMontreal;

export const metadata: Metadata = {
  title: "Marlon Martin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className}`}>{children}</body>
    </html>
  );
}
